#include "config/keys.h"

namespace ConfigKey {
namespace {
const std::vector<const char*> kAll = {
    ConfigKey::kUiScale,
    ConfigKey::kFontScale,
    ConfigKey::kTheme,
    ConfigKey::kButtonCorner,
    ConfigKey::kButtonOutline,
    ConfigKey::kAnimationEnabled,
    ConfigKey::kAnimationSpeedIndex,
    ConfigKey::kLanguage,
    ConfigKey::kNotificationEnabled,
    ConfigKey::kNotificationPosition,
    ConfigKey::kShowFps,
    ConfigKey::kFpsFormat,
    ConfigKey::kFpsPosition,
    ConfigKey::kShowClock,
    ConfigKey::kClockPosition,
    ConfigKey::kResolutionIndex,
    ConfigKey::kFullscreen,
    ConfigKey::kVsync,
    ConfigKey::kFpsLimit,
    ConfigKey::kAntiAliasing,
    ConfigKey::kWindowMode,
    ConfigKey::kRememberWindowSize,
    ConfigKey::kAutoPauseOnBlur,
    ConfigKey::kLastWindowWidth,
    ConfigKey::kLastWindowHeight,
    ConfigKey::kRenderScale,
    ConfigKey::kUpscaleMode,
    ConfigKey::kPostSaturation,
    ConfigKey::kPostContrast,
    ConfigKey::kPostBrightness,
    ConfigKey::kPostGamma,
    ConfigKey::kPostVignette,
    ConfigKey::kPostBloomStrength,
    ConfigKey::kPostBloomThreshold,
    ConfigKey::kPostChromatic,
    ConfigKey::kPostGrain,
    ConfigKey::kPostScanline,
    ConfigKey::kPostDither,
    ConfigKey::kParallax,
    ConfigKey::kParticles,
    ConfigKey::kPseudo3d,
    ConfigKey::kScreenShake,
    ConfigKey::kPlayerAnimation,
    ConfigKey::kAudioMasterVolume,
    ConfigKey::kAudioSoundEnabled,
    ConfigKey::kAudioSoundVolume,
    ConfigKey::kAudioBgmEnabled,
    ConfigKey::kAudioBgmVolume,
    ConfigKey::kLogLevel,
    ConfigKey::kLogRotate,
    ConfigKey::kLogKeep,
    ConfigKey::kGamepadEnabled,
    ConfigKey::kGamepadVibrationEnabled,
    ConfigKey::kGamepadVibrationIntensity,
    ConfigKey::kKeyLeft,
    ConfigKey::kKeyRight,
    ConfigKey::kKeyJump,
    ConfigKey::kKeyPause,
    ConfigKey::kKeyRestart,
    ConfigKey::kCurrentWallpaper,
    ConfigKey::kInitialLives,
    ConfigKey::kLevelIntro,
    ConfigKey::kPlayerName,
    ConfigKey::kShowColliders,
    ConfigKey::kConsoleAutoScroll,
    ConfigKey::kConsoleBlinkCursor,
    ConfigKey::kConsoleFontSize,
    ConfigKey::kConsoleHistoryLines,
    ConfigKey::kConsoleLineHeight,
    ConfigKey::kConsoleMask,
    ConfigKey::kConsolePanelAlpha,
    ConfigKey::kConsolePrompt,
    ConfigKey::kUiSoundEnabled,
    ConfigKey::kNotificationDuration,
    ConfigKey::kParticleDensity,
    ConfigKey::kShakeIntensity,
};
} // namespace

const std::vector<const char*>& allKeys() {
    return kAll;
}

} // namespace ConfigKey
